# Springboot configurations
spring.datasource:
  url: ${aws.rds.hostname}
  driver-class-name: org.mariadb.jdbc.Driver
  username: ${aws.rds.username}
  password: ${aws.rds.password}

spring.jpa:
  hibernate:
    ddl-auto: none # do not change